<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from AssignmentStatementRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class AssignmentStatementRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/assignment-statement-rule',
            name: 'AssignmentStatementRule',
            description: 'Transpiled from PHPStan\'s AssignmentStatementRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::ExpressionStatement];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::isAssignment(Support::nthExpression($context, $node, 0)))) {
            return;
        }

        if (!(Support::isVariable(Support::nthExpression($context, Support::nthExpression($context, $node, 0), 0)))) {
            return;
        }

        if (!(Support::directVariableName($context, Support::nthExpression($context, Support::nthExpression($context, $node, 0), 0)) === 'result')) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.assignmentStatement',
            Issue::new(Support::viaTraitUsers($context, $node, 'Do not assign to $result'), $node->span, 'here'),
        );
    }

}

