<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from BoundNameComparisonRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class BoundNameComparisonRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/bound-name-comparison-rule',
            name: 'BoundNameComparisonRule',
            description: 'Transpiled from PHPStan\'s BoundNameComparisonRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::Method];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (Support::declarationName($context, $node) === '__construct') {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.boundNameComparison',
            Issue::new(Support::viaTraitUsers($context, $node, 'Name the constructor __construct'), $node->span, 'here'),
        );
    }

}

