<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from ClassConstantIsAStringRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class ClassConstantIsAStringRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/class-constant-is-a-string-rule',
            name: 'ClassConstantIsAStringRule',
            description: 'Transpiled from PHPStan\'s ClassConstantIsAStringRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::Class_];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        // guard dropped: a declaration hook fires inside a class-like, so there is always an enclosing class
        if (!(Support::namesContain(Support::parentClassNames($context, $node), 'PHPStan\\Rules\\Rule'))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.classConstantIsAString',
            Issue::new(Support::viaTraitUsers($context, $node, 'Do not implement the rule interface directly'), $node->span, 'here'),
        );
    }

}

