<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from ClassifiedCodeRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class ClassifiedCodeRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/classified-code-rule',
            name: 'ClassifiedCodeRule',
            description: 'Transpiled from PHPStan\'s ClassifiedCodeRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::FunctionCall];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::isName(Support::nthExpression($context, $node, 0)))) {
            return;
        }

        if (!(Support::bytesIsOneOf(Support::textOf(Support::nthExpression($context, $node, 0)), ['dump', 'dd']))) {
            return;
        }

        $area = ((Support::enclosingNamespace($context) === null ? false : ('App' === Support::enclosingNamespace($context) ? true : Support::bytesStartWith(Support::enclosingNamespace($context), 'App\\'))) ? 'App' : ((Support::enclosingNamespace($context) === null ? false : ('Tests' === Support::enclosingNamespace($context) ? true : Support::bytesStartWith(Support::enclosingNamespace($context), 'Tests\\'))) ? 'Tests' : null));
        if ($area === null) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.noDebugIn' . $area,
            Issue::new(Support::viaTraitUsers($context, $node, sprintf('No debug statements in the %s namespace', $area)), $node->span, 'here'),
        );
    }

}

