<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from CombinedMethodCallRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\AfterAnalysisContext;
use Mago\Sdk\Analyzer\AfterAnalysisHook;
use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\FormRequestFields;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class CombinedMethodCallRule implements Plugin, NodeAnalysisHook, AfterAnalysisHook
{

    /** Carried from the rule, whose derivation names it. */
    private const array METHOD_DEBUG_STATEMENTS = ['dump' => true, 'dd' => true, 'ddd' => true, 'ray' => true];
    private readonly array $unsafeMethodsLookup;
    private readonly array $fieldAccessorsLookup;
    private readonly array $quickRejectLookup;

    public function __construct(
        public readonly array $unsafeMethods = ['input', 'all', 'get', 'query', 'post', 'only', 'except', 'collect', 'string', 'str', 'integer', 'boolean', 'float', 'json', 'keys', 'fluent', 'array', 'date', 'enum', 'enums', 'file', 'allFiles'],
        public readonly array $fieldAccessors = ['input', 'get', 'query', 'post', 'string', 'str', 'integer', 'boolean', 'float', 'json', 'array', 'collect', 'date', 'enum', 'enums', 'file'],
        public readonly array $namespaces = ['App'],
        public readonly array $excludeNamespaces = ['App\\Providers', 'App\\Http\\Responses'],
        public readonly array $firstPartyNamespaces = ['App', 'Database\\Factories', 'Tests'],
    ) {
        $this->unsafeMethodsLookup = array_fill_keys(array_map(strtolower(...), $unsafeMethods), true);
        $this->fieldAccessorsLookup = array_fill_keys(array_map(strtolower(...), $fieldAccessors), true);
        $this->quickRejectLookup = $this->unsafeMethodsLookup + $this->fieldAccessorsLookup + self::METHOD_DEBUG_STATEMENTS;
    }

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/combined-method-call-rule',
            name: 'CombinedMethodCallRule',
            description: 'Transpiled from PHPStan\'s CombinedMethodCallRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
        $registry->registerAfterAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::MethodCall];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText, FileAnalysisRequirement::ReceiverType];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::selectorIsIdentifier(Support::selector($context, $node)))) {
            return;
        }

        $this->checkFlagError($context, $node);
        if (!(isset($this->quickRejectLookup[Support::lowerBytes(Support::textOf(Support::selector($context, $node)))]))) {
            return;
        }

        $this->checkChainedDebugError($context, $node);
        $this->checkUnsafeRequestDataError($context, $node);
    }

    public function afterAnalysis(AfterAnalysisContext $context): void
    {
        FormRequestFields::report($context, $this->fieldAccessorsLookup, $this->namespaces, $this->excludeNamespaces, 'hihaho.validation.unvalidatedFormRequestField');
    }

    private function checkFlagError(NodeAnalysisContext $context, mixed $node): void
    {
        if (!(Support::selectorIsIdentifier(Support::selector($context, $node)))) {
            return;
        }

        if (Support::argCount(Support::argumentList($context, $node)) === 0) {
            return;
        }

        if (!((Support::argumentIsNamed(Support::argumentAt(Support::argumentList($context, $node), Support::argCount(Support::argumentList($context, $node)) - 1)) || Support::argumentIsUnpacked(Support::argumentAt(Support::argumentList($context, $node), Support::argCount(Support::argumentList($context, $node)) - 1)) ? false : (Support::isConstantName(Support::argumentValue(Support::argumentAt(Support::argumentList($context, $node), Support::argCount(Support::argumentList($context, $node)) - 1)))) && (Support::bytesIsOneOf(Support::lowerBytes(Support::constantNameText(Support::argumentValue(Support::argumentAt(Support::argumentList($context, $node), Support::argCount(Support::argumentList($context, $node)) - 1)))), ['true', 'false', 'null']))))) {
            return;
        }

        foreach (Support::arguments(Support::argumentList($context, $node)) as $arg) {
            if (Support::argumentIsNamed($arg) || Support::argumentIsUnpacked($arg)) {
                return;
            }

        }

        // guard dropped: an index produced behind guards is never null once those guards have run
        if (!(Support::soleObjectClassIgnoringNull($context->receiverType) !== null) || !(Support::methodExists($context, Support::soleObjectClassIgnoringNull($context->receiverType), Support::textOf(Support::selector($context, $node))))) {
            return;
        }

        if (!((Support::anyOf($this->firstPartyNamespaces, static fn ($item): bool => Support::bytesStartWith(Support::declaringClassOfMethod($context, Support::soleObjectClassIgnoringNull($context->receiverType), Support::textOf(Support::selector($context, $node))), (rtrim($item, '\\') . '\\'))) ? true : false))) {
            return;
        }

        if (! Support::hasParameterAt($context, Support::soleObjectClassIgnoringNull($context->receiverType), Support::textOf(Support::selector($context, $node)), Support::argCount(Support::argumentList($context, $node)) - 1) || Support::parameterIsVariadic($context, Support::soleObjectClassIgnoringNull($context->receiverType), Support::textOf(Support::selector($context, $node)), Support::argCount(Support::argumentList($context, $node)) - 1)) {
            return;
        }

        $context->report(
            Level::Error,
            'hihaho.conventions.positionalFlagArgument',
            Issue::new(sprintf('Pass a named argument (%s: ...) for the bool/null flag — it is opaque positionally.', Support::parameterName($context, Support::soleObjectClassIgnoringNull($context->receiverType), Support::textOf(Support::selector($context, $node)), Support::argCount(Support::argumentList($context, $node)) - 1)), $node->span, 'here'),
        );

    }

    private function checkChainedDebugError(NodeAnalysisContext $context, mixed $node): void
    {
        if (!(Support::selectorIsOneOf(Support::selector($context, $node), ['dump', 'dd', 'ddd', 'ray']))) {
            return;
        }

        $namespace = (((Support::enclosingNamespace($context) === null ? false : ('App' === Support::enclosingNamespace($context) ? true : Support::bytesStartWith(Support::enclosingNamespace($context), 'App\\')))) ? 'App' : (((Support::enclosingNamespace($context) === null ? false : ('Tests' === Support::enclosingNamespace($context) ? true : Support::bytesStartWith(Support::enclosingNamespace($context), 'Tests\\')))) ? 'Tests' : null));
        if ($namespace === null) {
            return;
        }

        if (!((Support::objectClasses($context->receiverType) === [] ? false : (Support::anyOf(Support::objectClasses($context->receiverType), static fn ($item): bool => (!(!(Support::methodExists($context, $item, Support::textOf(Support::selector($context, $node))))) && Support::bytesStartWith(Support::declaringClassOfMethod($context, $item, Support::textOf(Support::selector($context, $node))), 'Illuminate\\'))) ? true : false)))) {
            return;
        }

        $context->report(
            Level::Error,
            'hihaho.debug.noChainedDebugIn' . $namespace,
            Issue::new(sprintf('No chained debug statements should be present in the %s namespace.', $namespace), $node->span, 'here'),
        );

    }

    private function checkUnsafeRequestDataError(NodeAnalysisContext $context, mixed $node): void
    {
        if (!(isset($this->unsafeMethodsLookup[Support::lowerBytes(Support::textOf(Support::selector($context, $node)))]))) {
            return;
        }

        if (!((Support::anyOf($this->namespaces, static fn ($item): bool => (Support::enclosingNamespace($context) === null ? false : ($item === Support::enclosingNamespace($context) ? true : Support::bytesStartWith(Support::enclosingNamespace($context), (rtrim($item, '\\') . '\\'))))) ? true : false)) || ((Support::anyOf($this->excludeNamespaces, static fn ($item): bool => (Support::enclosingNamespace($context) === null ? false : ($item === Support::enclosingNamespace($context) ? true : Support::bytesStartWith(Support::enclosingNamespace($context), (rtrim($item, '\\') . '\\'))))) ? true : false))) {
            return;
        }

        if (Support::isInClass($context, $node) && (Support::classDescendsFrom($context, Support::enclosingClassName($context, $node), 'Illuminate\\Http\\Request'))) {
            return;
        }

        if (!((Support::anyOf(Support::objectClasses($context->receiverType), static fn ($item): bool => Support::classDescendsFrom($context, $item, 'Illuminate\\Http\\Request')) ? true : false))) {
            return;
        }

        $context->report(
            Level::Error,
            'hihaho.validation.noUnsafeRequestData',
            Issue::new(sprintf('Reading unvalidated request data via %s() is not allowed. Use a FormRequest, $request->validated(), or $request->safe().', Support::textOf(Support::selector($context, $node))), $node->span, 'here'),
        );

    }

}

