<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from CompoundClassGuardRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class CompoundClassGuardRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/compound-class-guard-rule',
            name: 'CompoundClassGuardRule',
            description: 'Transpiled from PHPStan\'s CompoundClassGuardRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::Class_, NodeKind::Enum, NodeKind::Interface];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (Support::declarationKindIs($context, $node, 'Class') && Support::declarationIsAbstract($context, $node)) {
            return;
        }

        if (!(Support::bytesContain(Support::enclosingClassName($context, $node), 'Reported'))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.compoundClassGuard',
            Issue::new('Declaration is not allowed here', $node->span, 'here'),
        );
    }

}

