<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from ConfigClosureRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class ConfigClosureRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/config-closure-rule',
            name: 'ConfigClosureRule',
            description: 'Transpiled from PHPStan\'s ConfigClosureRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::Closure];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!((count(Support::declaredParams($context, $node)) === 1) && ((Support::hintIsName(Support::declaredParamHint(Support::declaredParamAt($context, $node, 0)))) && (Support::hintNameIs($context, Support::declaredParamHint(Support::declaredParamAt($context, $node, 0)), 'Examples\\Config\\Configurator'))))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.configClosure',
            Issue::new(Support::viaTraitUsers($context, $node, 'This config closure is registered twice'), $node->span, 'here'),
        );
    }

}

