<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from ConstantSetRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class ConstantSetRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/constant-set-rule',
            name: 'ConstantSetRule',
            description: 'Transpiled from PHPStan\'s ConstantSetRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::FunctionCall];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::isName(Support::nthExpression($context, $node, 0)))) {
            return;
        }

        if (!(Support::bytesIsOneOf(Support::textOf(Support::nthExpression($context, $node, 0)), ['dump', 'dd', 'var_dump']))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.constantSet',
            Issue::new('No debug calls', $node->span, 'here'),
        );
    }

}

