<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from ConstructedLookupRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class ConstructedLookupRule implements Plugin, NodeAnalysisHook
{

    /** @var array<string, mixed> */
    private readonly array $built;

    public function __construct() {
        $this->built = array_fill_keys(['dump', 'dd'], true);
    }

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/constructed-lookup-rule',
            name: 'ConstructedLookupRule',
            description: 'Transpiled from PHPStan\'s ConstructedLookupRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::FunctionCall];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::isName(Support::nthExpression($context, $node, 0)))) {
            return;
        }

        if (!(Support::lookupHas($this->built, Support::textOf(Support::nthExpression($context, $node, 0))))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.constructedLookup',
            Issue::new(Support::viaTraitUsers($context, $node, 'Do not call a debug helper'), $node->span, 'here'),
        );
    }

}

