<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from DeepHelperChainRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class DeepHelperChainRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/deep-helper-chain-rule',
            name: 'DeepHelperChainRule',
            description: 'Transpiled from PHPStan\'s DeepHelperChainRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::FunctionCall];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::isName(Support::nthExpression($context, $node, 0)))) {
            return;
        }

        if (!((((((Support::isName(Support::nthExpression($context, $node, 0)) && Support::nameEquals(Support::nthExpression($context, $node, 0), 'forbidden')))))))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.deepHelperChain',
            Issue::new('Do not call forbidden()', $node->span, 'here'),
        );
    }

}

