<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from EarlyThenTailReportRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class EarlyThenTailReportRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/early-then-tail-report-rule',
            name: 'EarlyThenTailReportRule',
            description: 'Transpiled from PHPStan\'s EarlyThenTailReportRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::Class_];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(! Support::declarationKindIs($context, $node, 'AnonymousClass'))) {
            return;
        }

        if (Support::bytesStartWith(Support::declarationName($context, $node), 'Abstract')) {
            $context->report(
                Level::Error,
                'fixture.earlyThenTail.abstract',
                Issue::new(Support::viaTraitUsers($context, $node, 'Named for an abstraction.'), $node->span, 'here'),
            );

            return;
        }

        if (Support::bytesEndWith(Support::declarationName($context, $node), 'Repository')) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.earlyThenTail.other',
            Issue::new(Support::viaTraitUsers($context, $node, 'Named for nothing in particular.'), $node->span, 'here'),
        );
    }

}

