<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from EveryExpressionRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class EveryExpressionRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/every-expression-rule',
            name: 'EveryExpressionRule',
            description: 'Transpiled from PHPStan\'s EveryExpressionRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::ClassConstantAccess, NodeKind::StaticPropertyAccess, NodeKind::MethodCall, NodeKind::StaticMethodCall, NodeKind::FunctionCall, NodeKind::PropertyAccess];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        $this->checkStaticPropertyAccess($context, $node);
        $this->checkMethodCall($context, $node);
    }

    private function checkStaticPropertyAccess(NodeAnalysisContext $context, mixed $node): void
    {
        if (!(Support::nodeKindIs($context, $node, 'StaticPropertyAccess'))) {
            return;
        }

        if (!(! Support::isWrittenName(Support::namePart($context, $node)))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.everyExpression',
            Issue::new('Name it out', $node->span, 'here'),
        );

    }

    private function checkMethodCall(NodeAnalysisContext $context, mixed $node): void
    {
        if (!(Support::nodeKindIs($context, $node, 'MethodCall') || Support::nodeKindIs($context, $node, 'FunctionCall'))) {
            return;
        }

        if (!(! Support::isWrittenName(Support::namePart($context, $node)))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.everyExpression',
            Issue::new('Name it out', $node->span, 'here'),
        );

    }

}

