<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from ForbiddenStaticConstFetchRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class ForbiddenStaticConstFetchRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/forbidden-static-const-fetch-rule',
            name: 'ForbiddenStaticConstFetchRule',
            description: 'Transpiled from PHPStan\'s ForbiddenStaticConstFetchRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::ClassConstantAccess];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::isName(Support::classPart($context, $node)))) {
            return;
        }

        if (!(Support::nameEquals(Support::classPart($context, $node), 'static'))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.forbiddenStaticConstFetch',
            Issue::new('Avoid static access of constants', $node->span, 'here'),
        );
    }

}

