<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from MidBodyCacheRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class MidBodyCacheRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/mid-body-cache-rule',
            name: 'MidBodyCacheRule',
            description: 'Transpiled from PHPStan\'s MidBodyCacheRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::FunctionCall];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::isName(Support::nthExpression($context, $node, 0)))) {
            return;
        }

        if (!((Support::enclosingNamespace($context) === null ? false : Support::lowerBytes(Support::textOf(Support::nthExpression($context, $node, 0))) === 'dump'))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.midBodyCache',
            Issue::new('No dump() in a namespaced file', $node->span, 'here'),
        );
    }

}

