<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from NativeReflectionHopRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class NativeReflectionHopRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/native-reflection-hop-rule',
            name: 'NativeReflectionHopRule',
            description: 'Transpiled from PHPStan\'s NativeReflectionHopRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::Method];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        // guard dropped: this hook fires only on a class-like or one of its members, so the scope it carries is always in a class
        if (!(Support::declarationKindIs($context, $node, 'Interface'))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.nativeReflectionHop',
            Issue::new(Support::viaTraitUsers($context, $node, 'Declare this method on a class rather than an interface'), $node->span, 'here'),
        );
    }

}

