<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from ObjectTypedAssignRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class ObjectTypedAssignRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/object-typed-assign-rule',
            name: 'ObjectTypedAssignRule',
            description: 'Transpiled from PHPStan\'s ObjectTypedAssignRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::ExpressionStatement];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText, FileAnalysisRequirement::ExpressionTypes];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::isAssignment(Support::nthExpression($context, $node, 0)))) {
            return;
        }

        if (!(Support::typeIsObject(Support::expressionType($context, Support::nthExpression($context, Support::nthExpression($context, $node, 0), 1))))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.objectTypedAssign',
            Issue::new(Support::viaTraitUsers($context, $node, 'Do not assign an object here'), $node->span, 'here'),
        );
    }

}

