<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from OnlyAllowFacadeAliasInBlade. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\AfterAnalysisContext;
use Mago\Sdk\Analyzer\AfterAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Sandermuller\PhpstanToMago\Runtime\FacadeAliases;

final class OnlyAllowFacadeAliasInBlade implements AfterAnalysisHook, Plugin
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/only-allow-facade-alias-in-blade',
            name: 'OnlyAllowFacadeAliasInBlade',
            description: 'Transpiled from PHPStan\'s OnlyAllowFacadeAliasInBlade.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerAfterAnalysisHook($this);
    }

    /** @return list<never> */
    public function getTargets(): array
    {
        return [];
    }

    /** @return list<never> */
    public function getRequirements(): array
    {
        return [];
    }

    public function afterAnalysis(AfterAnalysisContext $context): void
    {
        FacadeAliases::report($context, 'hihaho.generic.onlyAllowFacadeAliasInBlade');
    }
}

