<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from PositionalFlagRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class PositionalFlagRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/positional-flag-rule',
            name: 'PositionalFlagRule',
            description: 'Transpiled from PHPStan\'s PositionalFlagRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::Instantiation];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::isName(Support::classPart($context, $node)))) {
            return;
        }

        if (Support::argCount(Support::argumentList($context, $node)) === 0) {
            return;
        }

        if (!((Support::argumentIsNamed(Support::argumentAt(Support::argumentList($context, $node), Support::argCount(Support::argumentList($context, $node)) - 1)) || Support::argumentIsUnpacked(Support::argumentAt(Support::argumentList($context, $node), Support::argCount(Support::argumentList($context, $node)) - 1)) ? false : (Support::isConstantName(Support::argumentValue(Support::argumentAt(Support::argumentList($context, $node), Support::argCount(Support::argumentList($context, $node)) - 1)))) && (Support::bytesIsOneOf(Support::lowerBytes(Support::constantNameText(Support::argumentValue(Support::argumentAt(Support::argumentList($context, $node), Support::argCount(Support::argumentList($context, $node)) - 1)))), ['true', 'false', 'null']))))) {
            return;
        }

        foreach (Support::arguments(Support::argumentList($context, $node)) as $arg) {
            if (Support::argumentIsNamed($arg) || Support::argumentIsUnpacked($arg)) {
                return;
            }

        }

        // guard dropped: an index produced behind guards is never null once those guards have run
        if (!(Support::classExists($context, Support::resolvedName($context, Support::classPart($context, $node))))) {
            return;
        }

        if (!(Support::methodExists($context, Support::resolvedName($context, Support::classPart($context, $node)), '__construct'))) {
            return;
        }

        if (!((Support::anyOf(['Examples'], static fn ($item): bool => Support::bytesStartWith(Support::declaringClassOfMethod($context, Support::resolvedName($context, Support::classPart($context, $node)), '__construct'), (rtrim($item, '\\') . '\\'))) ? true : false))) {
            return;
        }

        if (! Support::hasParameterAt($context, Support::resolvedName($context, Support::classPart($context, $node)), '__construct', Support::argCount(Support::argumentList($context, $node)) - 1) || Support::parameterIsVariadic($context, Support::resolvedName($context, Support::classPart($context, $node)), '__construct', Support::argCount(Support::argumentList($context, $node)) - 1)) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.positionalFlagArgument',
            Issue::new(sprintf('Pass a named argument (%s: ...) for the bool/null flag — it is opaque positionally.', Support::parameterName($context, Support::resolvedName($context, Support::classPart($context, $node)), '__construct', Support::argCount(Support::argumentList($context, $node)) - 1)), $node->span, 'here'),
        );
    }

}

