<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from QuotedClassNameMessageRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class QuotedClassNameMessageRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/quoted-class-name-message-rule',
            name: 'QuotedClassNameMessageRule',
            description: 'Transpiled from PHPStan\'s QuotedClassNameMessageRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::ClassConstantAccess];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::isName(Support::classPart($context, $node)))) {
            return;
        }

        if (!(Support::nameEquals(Support::classPart($context, $node), 'static'))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.quotedClassNameMessage',
            Issue::new(sprintf('Constant access must go through "%s" instead', 'Acme\\Contract\\Repository\\ServiceRepositoryInterface'), $node->span, 'here'),
        );
    }

}

