<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from ThrowingAssertionGuardRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class ThrowingAssertionGuardRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/throwing-assertion-guard-rule',
            name: 'ThrowingAssertionGuardRule',
            description: 'Transpiled from PHPStan\'s ThrowingAssertionGuardRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::Method];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        // guard dropped: this hook fires only on a class-like or one of its members, so the scope it carries is always in a class
        if (!(Support::declarationName($context, $node) === 'handle')) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.throwingAssertionGuard',
            Issue::new(Support::viaTraitUsers($context, $node, 'A method named handle belongs on a handler'), $node->span, 'here'),
        );
    }

}

