<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from TwoChecksRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class TwoChecksRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/two-checks-rule',
            name: 'TwoChecksRule',
            description: 'Transpiled from PHPStan\'s TwoChecksRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::FunctionCall];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        if (!(Support::isName(Support::nthExpression($context, $node, 0)))) {
            return;
        }

        $namespace = (!(Support::enclosingNamespace($context) === null) && Support::bytesStartWith(Support::enclosingNamespace($context), 'Checks\\') ? 'Checks' : (!(Support::enclosingNamespace($context) === null) && Support::bytesStartWith(Support::enclosingNamespace($context), 'Probes\\') ? 'Probes' : null));
        if ($namespace === null) {
            return;
        }

        $this->checkDebugError($context, $node, $namespace);
        $this->checkInvadeError($context, $node, $namespace);
    }

    private function checkDebugError(NodeAnalysisContext $context, mixed $node, mixed $namespace): void
    {
        if (!(Support::isName(Support::nthExpression($context, $node, 0))) || !(Support::nameEquals(Support::nthExpression($context, $node, 0), 'dump'))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.twoChecks.debug',
            Issue::new(Support::viaTraitUsers($context, $node, sprintf('No dump() in the %s namespace', $namespace)), $node->span, 'here'),
        );

    }

    private function checkInvadeError(NodeAnalysisContext $context, mixed $node, mixed $namespace): void
    {
        if (!(Support::isName(Support::nthExpression($context, $node, 0))) || !(Support::nameEquals(Support::nthExpression($context, $node, 0), 'invade'))) {
            return;
        }

        $context->report(
            Level::Error,
            'fixture.twoChecks.invade',
            Issue::new(Support::viaTraitUsers($context, $node, sprintf('No invade() in the %s namespace', $namespace)), $node->span, 'here'),
        );

    }

}

