<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from UppercaseConstantRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\FileAnalysisRequirement;
use Mago\Sdk\Analyzer\NodeAnalysisContext;
use Mago\Sdk\Analyzer\NodeAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Mago\Sdk\Syntax\NodeKind;
use Sandermuller\PhpstanToMago\Runtime\Support;

final class UppercaseConstantRule implements Plugin, NodeAnalysisHook
{

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/uppercase-constant-rule',
            name: 'UppercaseConstantRule',
            description: 'Transpiled from PHPStan\'s UppercaseConstantRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerNodeAnalysisHook($this);
    }

    public function getTargets(): array
    {
        return [NodeKind::ClassLikeConstant];
    }

    public function getRequirements(): array
    {
        return [FileAnalysisRequirement::TargetSubtree, FileAnalysisRequirement::SourceText];
    }

    public function analyze(NodeAnalysisContext $context): void
    {
        $node = $context->node;

        foreach (Support::constantItems($context, $node) as $const_) {
            if (Support::isUppercase(Support::constantItemName($const_))) {
                continue;
            }

            $context->report(
                Level::Error,
                'fixture.uppercaseConstant',
                Issue::new(Support::viaTraitUsers($context, $node, sprintf('Constant "%s" must be uppercase', Support::constantItemName($const_))), $node->span, 'here'),
            );

            return;
        }

    }

}

