// GENERATED by phpstan-to-mago from ForbiddenStaticConstFetchRule. Do not edit by hand.
use mago_allocator::Arena;
use schemars::JsonSchema;

use mago_reporting::Annotation;
use mago_reporting::Issue;
use mago_reporting::Level;
use mago_span::HasSpan;
use mago_syntax::cst::Node;
use mago_syntax::cst::NodeKind;

use crate::category::Category;
use crate::context::LintContext;
use crate::requirements::RuleRequirements;
use crate::rule::Config;
use crate::rule::LintRule;
use crate::rule::transpiled::support;
use crate::rule_meta::RuleMeta;
use crate::settings::RuleSettings;

#[derive(Debug, Clone)]
pub struct ForbiddenStaticConstFetchRule {
    cfg: ForbiddenStaticConstFetchRuleConfig,
}

#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash, JsonSchema)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(default, rename_all = "kebab-case", deny_unknown_fields))]
pub struct ForbiddenStaticConstFetchRuleConfig {
    pub level: Level,
}

impl Default for ForbiddenStaticConstFetchRuleConfig {
    fn default() -> Self {
        Self { level: Level::Error }
    }
}

impl Config for ForbiddenStaticConstFetchRuleConfig {
    fn level(&self) -> Level {
        self.level
    }

    fn default_enabled() -> bool {
        false
    }
}

impl LintRule for ForbiddenStaticConstFetchRule {
    type Config = ForbiddenStaticConstFetchRuleConfig;

    fn meta() -> &'static RuleMeta {
        const META: RuleMeta = RuleMeta {
            name: "ForbiddenStaticConstFetchRule",
            code: "fixture.forbiddenStaticConstFetch",
            description: "Transpiled from the PHPStan rule ForbiddenStaticConstFetchRule.",
            good_example: "<?php\n",
            bad_example: "<?php\n",
            category: Category::BestPractices,
            requirements: RuleRequirements::None,
        };

        &META
    }

    fn targets() -> &'static [NodeKind] {
        const TARGETS: &[NodeKind] = &[NodeKind::ClassConstantAccess];

        TARGETS
    }

    fn build(settings: &RuleSettings<Self::Config>) -> Self {
        Self { cfg: settings.config }
    }

    fn check<'arena, A>(&self, context: &mut LintContext<'_, 'arena, A>, node: Node<'_, 'arena>)
    where
        A: Arena,
    {
        let Node::ClassConstantAccess(node) = node else {
            return;
        };

        if !(support::is_name(node.class)) {
            return;
        }

        if !(support::name_equals(node.class, b"static")) {
            return;
        }

        context.collector.report(
            Issue::new(self.cfg.level, "Avoid static access of constants")
                .with_code("fixture.forbiddenStaticConstFetch")
                .with_annotation(Annotation::primary(node.span()).with_message("here")),
        );
    }
}
