// GENERATED by phpstan-to-mago from UppercaseConstantRule. Do not edit by hand.
use mago_allocator::Arena;
use schemars::JsonSchema;

use mago_reporting::Annotation;
use mago_reporting::Issue;
use mago_reporting::Level;
use mago_span::HasSpan;
use mago_syntax::cst::Node;
use mago_syntax::cst::NodeKind;

use crate::category::Category;
use crate::context::LintContext;
use crate::requirements::RuleRequirements;
use crate::rule::Config;
use crate::rule::LintRule;
use crate::rule::transpiled::support;
use crate::rule_meta::RuleMeta;
use crate::settings::RuleSettings;

#[derive(Debug, Clone)]
pub struct UppercaseConstantRule {
    cfg: UppercaseConstantRuleConfig,
}

#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash, JsonSchema)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(default, rename_all = "kebab-case", deny_unknown_fields))]
pub struct UppercaseConstantRuleConfig {
    pub level: Level,
}

impl Default for UppercaseConstantRuleConfig {
    fn default() -> Self {
        Self { level: Level::Error }
    }
}

impl Config for UppercaseConstantRuleConfig {
    fn level(&self) -> Level {
        self.level
    }

    fn default_enabled() -> bool {
        false
    }
}

impl LintRule for UppercaseConstantRule {
    type Config = UppercaseConstantRuleConfig;

    fn meta() -> &'static RuleMeta {
        const META: RuleMeta = RuleMeta {
            name: "UppercaseConstantRule",
            code: "fixture.uppercaseConstant",
            description: "Transpiled from the PHPStan rule UppercaseConstantRule.",
            good_example: "<?php\n",
            bad_example: "<?php\n",
            category: Category::BestPractices,
            requirements: RuleRequirements::None,
        };

        &META
    }

    fn targets() -> &'static [NodeKind] {
        const TARGETS: &[NodeKind] = &[NodeKind::ClassLikeConstant];

        TARGETS
    }

    fn build(settings: &RuleSettings<Self::Config>) -> Self {
        Self { cfg: settings.config }
    }

    fn check<'arena, A>(&self, context: &mut LintContext<'_, 'arena, A>, node: Node<'_, 'arena>)
    where
        A: Arena,
    {
        let Node::ClassLikeConstant(node) = node else {
            return;
        };

        for const_ in node.items.iter() {
            if support::is_uppercase(support::constant_item_name(const_)) {
                continue;
            }

            context.collector.report(
                Issue::new(self.cfg.level, format!("Constant \"{}\" must be uppercase", String::from_utf8_lossy(support::constant_item_name(const_))))
                    .with_code("fixture.uppercaseConstant")
                    .with_annotation(Annotation::primary(node.span()).with_message("here")),
            );
            return;
        }

    }
}
