// GENERATED by phpstan-to-mago from ForbiddenStaticConstFetchRule. Do not edit by hand.
pub struct ForbiddenStaticConstFetchRule;

static FORBIDDEN_STATIC_CONST_FETCH_RULE_META: ProviderMeta =
    ProviderMeta::new("transpiled::forbidden_static_const_fetch_rule", "ForbiddenStaticConstFetchRule", "generated");

impl Provider for ForbiddenStaticConstFetchRule {
    fn meta() -> &'static ProviderMeta {
        &FORBIDDEN_STATIC_CONST_FETCH_RULE_META
    }
}

impl ExpressionHook for ForbiddenStaticConstFetchRule {
    fn after_expression(&self, node: &Expression<'_>, context: &mut HookContext<'_, '_>) -> HookResult<()> {
        let Some(node) = support::as_class_constant_access(node) else {
            return Ok(());
        };

        if !(support::is_name(node.class)) {
            return Ok(());
        }

        if !(support::name_equals(node.class, b"static")) {
            return Ok(());
        }

        context.report(
            IssueCode::InvalidArgument,
            Issue::error("Avoid static access of constants")
                .with_code("fixture.forbiddenStaticConstFetch")
                .with_annotation(Annotation::primary(node.span()).with_message("here")),
        );

        Ok(())
    }
}
