// GENERATED by phpstan-to-mago from QuotedClassNameMessageRule. Do not edit by hand.
pub struct QuotedClassNameMessageRule;

static QUOTED_CLASS_NAME_MESSAGE_RULE_META: ProviderMeta =
    ProviderMeta::new("transpiled::quoted_class_name_message_rule", "QuotedClassNameMessageRule", "generated");

impl Provider for QuotedClassNameMessageRule {
    fn meta() -> &'static ProviderMeta {
        &QUOTED_CLASS_NAME_MESSAGE_RULE_META
    }
}

impl ExpressionHook for QuotedClassNameMessageRule {
    fn after_expression(&self, node: &Expression<'_>, context: &mut HookContext<'_, '_>) -> HookResult<()> {
        let Some(node) = support::as_class_constant_access(node) else {
            return Ok(());
        };

        if !(support::is_name(node.class)) {
            return Ok(());
        }

        if !(support::name_equals(node.class, b"static")) {
            return Ok(());
        }

        context.report(
            IssueCode::InvalidArgument,
            Issue::error(format!("Constant access must go through \"{}\" instead", "Acme\\Contract\\Repository\\ServiceRepositoryInterface"))
                .with_code("fixture.quotedClassNameMessage")
                .with_annotation(Annotation::primary(node.span()).with_message("here")),
        );

        Ok(())
    }
}
