// GENERATED by phpstan-to-mago from UppercaseConstantRule. Do not edit by hand.
pub struct UppercaseConstantRule;

static UPPERCASE_CONSTANT_RULE_META: ProviderMeta =
    ProviderMeta::new("transpiled::uppercase_constant_rule", "UppercaseConstantRule", "generated");

impl Provider for UppercaseConstantRule {
    fn meta() -> &'static ProviderMeta {
        &UPPERCASE_CONSTANT_RULE_META
    }
}

impl ClassLikeMemberHook for UppercaseConstantRule {
    fn on_class_like_constant(&self, node: &ClassLikeConstant<'_>, _metadata: &ClassLikeMetadata, context: &mut HookContext<'_, '_>) -> HookResult<()> {
        for const_ in node.items.iter() {
            if support::is_uppercase(support::constant_item_name(const_)) {
                continue;
            }

            context.report(
                IssueCode::InvalidArgument,
                Issue::error(format!("Constant \"{}\" must be uppercase", String::from_utf8_lossy(support::constant_item_name(const_))))
                    .with_code("fixture.uppercaseConstant")
                    .with_annotation(Annotation::primary(node.span()).with_message("here")),
            );
            return Ok(());
        }


        Ok(())
    }
}
