<?php

declare(strict_types=1);

// GENERATED by phpstan-to-mago from ParamTypeCoverageRule. Do not edit by hand.

namespace Transpiled;

use Mago\Sdk\Analyzer\AfterAnalysisContext;
use Mago\Sdk\Analyzer\AfterAnalysisHook;
use Mago\Sdk\Analyzer\Plugin;
use Mago\Sdk\Analyzer\PluginDefinition;
use Mago\Sdk\Analyzer\PluginRegistry;
use Mago\Sdk\Reporting\Issue;
use Mago\Sdk\Reporting\Level;
use Sandermuller\PhpstanToMago\Runtime\TypeCoverage;

/**
 * Over-counts the original by up to 1.11% on the two Laravel consumers it was measured on: +81 of 13694 and +37
 * of 11428. The collector skips a method whose name an ancestor has, and PHPStan answers that from reflection
 * extensions a Mago plugin cannot reproduce. It can also *under*-count, by a separate cause: a class declared
 * twice in one file behind a version guard is counted by PHPStan and by neither body here, which is -7 on
 * nikic/php-parser. Reproduce either with `php tests/Support/run-coverage-corpus.php <consumer-root>`.
 */
final class ParamTypeCoverageRule implements AfterAnalysisHook, Plugin
{
    public function __construct(public readonly float $required = 99) {}

    public function getDefinition(): PluginDefinition
    {
        return new PluginDefinition(
            identifier: 'transpiled/param-type-coverage-rule',
            name: 'ParamTypeCoverageRule',
            description: 'Transpiled from PHPStan\'s ParamTypeCoverageRule.',
        );
    }

    public function register(PluginRegistry $registry): void
    {
        $registry->registerAfterAnalysisHook($this);
    }

    /** @return list<never> */
    public function getTargets(): array
    {
        return [];
    }

    /** @return list<never> */
    public function getRequirements(): array
    {
        return [];
    }

    public function afterAnalysis(AfterAnalysisContext $context): void
    {
        $coverage = TypeCoverage::parameters($context);
        if ($coverage->total === 0 || $coverage->percentage() >= $this->required) {
            return;
        }

        $message = sprintf(
            'Out of %d possible param types, only %d - %.1f %% actually have it. Add more param types to get over %s %%',
            $coverage->total,
            $coverage->typed,
            $coverage->percentage(),
            $this->required,
        );

        foreach ($coverage->missing as $location) {
            $context->report(Level::Error, 'typeCoverage.paramTypeCoverage', Issue::at($message, $location));
        }
    }
}
