<?php

declare(strict_types=1);

namespace Sandermuller\PhpstanToMago;

/**
 * Renders a {@see StatusReport} as a page a person reads.
 *
 * Two formats over one model, so a count cannot differ between them. Markdown is the testable one — it
 * diffs, it snapshots, and it renders wherever a repository is read. HTML is for looking at.
 *
 * Every number here carries its configuration, because the same count is correct twice over for different
 * targets and a reader with no target on the page concludes the tool is inconsistent.
 */
final class StatusPage
{
    public static function markdown(StatusReport $report): string
    {
        $lines = [
            '# PHPStan rules on mago',
            '',
            sprintf(
                'GENERATED by phpstan-to-mago for the `%s` target. %d of %d portable rules run, across the %d '
                . 'rule packages installed here.',
                $report->target,
                $report->emitted(),
                $report->portable(),
                count($report->packages),
            ),
            '',
            'That denominator is this install. Any figure quoting a fixed set of packages counts something',
            'else, so two correct numbers will differ. The package list below is the configuration behind',
            'this one.',
            '',
            'A rule runs when this tool could translate its body. One that could not is listed below with the',
            'construct that stopped it, so the gap is legible rather than a number to take on trust. A refused',
            'rule still runs under PHPStan. It is only missing from mago.',
            '',
            '`ships` counts every rule class in the package. `registers` counts the ones it wires in a neon of',
            'its own. A rule it wires nowhere cannot run for anybody, whatever this tool does with it, so the',
            'coverage figure uses that smaller number. `refused` means not translated yet, and that gap can',
            'close. `never` marks a rule no plugin could carry, which is why it sits outside the denominator.',
            '',
            'These are *translation* numbers: whether this tool could carry a rule body across. They do not',
            'say what a rule finds. Some packages ship rules that report nothing until a project configures',
            'what they forbid, and those read as 0 here whether or not their bodies would translate. Whether',
            'a rule is worth carrying is a different question, and this page does not answer it.',
            '',
            sprintf('Generated %s. Re-run `%s` to update it.', $report->generatedAt, $report->command),
            '',
            '| package | version | ships | registers | runs | refused | never |',
            '|:--|:--|--:|--:|--:|--:|--:|',
        ];

        foreach ($report->packages as $package) {
            $lines[] = sprintf(
                '| `%s` | %s | %d | %d | %d | %d | %d |',
                $package->package,
                $report->versions[$package->package] ?? 'unknown',
                $package->ships(),
                count($package->registered()),
                $package->emitted(),
                $package->refused(),
                $package->never(),
            );
        }

        foreach ($report->packages as $package) {
            $lines[] = '';
            $lines[] = sprintf(
                '## %s — %d of %d run',
                $package->package,
                $package->emitted(),
                $package->portable(),
            );
            $lines[] = '';

            foreach ($package->registered() as $outcome) {
                if ($outcome->emitted()) {
                    $lines[] = 'RUNS    ' . $outcome->name;

                    continue;
                }

                // `NEVER` is not a gap to close. Those rules report nothing a plugin could carry, so no
                // vocabulary entry reaches them and a reader sizing work from this page should skip them.
                $label = $outcome->verdict === RuleOutcome::NEVER ? 'NEVER   ' : 'REFUSED ';
                $lines[] = $label . $outcome->name . "\n        " . $outcome->reason;
            }
        }

        return implode("\n", $lines) . "\n";
    }

    public static function html(StatusReport $report): string
    {
        $rows = '';
        foreach ($report->packages as $package) {
            $share = $package->portable() === 0
                ? 0
                : (int) round($package->emitted() / $package->portable() * 100);

            $rows .= sprintf(
                '<tr><td class="pkg">%s</td><td class="ver">%s</td><td>%d</td><td>%d</td>'
                . '<td class="runs">%d</td><td>%d</td><td>%d</td>'
                . "<td class=\"bar\"><i style=\"width: %d%%\"></i></td></tr>\n",
                self::escape($package->package),
                self::escape($report->versions[$package->package] ?? 'unknown'),
                $package->ships(),
                count($package->registered()),
                $package->emitted(),
                $package->refused(),
                $package->never(),
                $share,
            );
        }

        $sections = '';
        foreach ($report->packages as $package) {
            $items = '';
            foreach ($package->registered() as $outcome) {
                if ($outcome->emitted()) {
                    $items .= '<li class="runs"><span class="tag">RUNS</span><span class="name">'
                        . self::escape($outcome->name) . "</span></li>\n";

                    continue;
                }

                $label = $outcome->verdict === RuleOutcome::NEVER ? 'NEVER' : 'REFUSED';
                $items .= sprintf(
                    '<li class="%s"><span class="tag">%s</span><span class="name">%s</span>'
                    . "<p>%s</p></li>\n",
                    strtolower($label),
                    $label,
                    self::escape($outcome->name),
                    self::escape($outcome->reason ?? ''),
                );
            }

            $sections .= sprintf(
                "<section><h2>%s <small>%d of %d run</small></h2><ul>\n%s</ul></section>\n",
                self::escape($package->package),
                $package->emitted(),
                $package->portable(),
                $items,
            );
        }

        $total = $report->portable() === 0 ? 0 : (int) round($report->emitted() / $report->portable() * 100);
        $packages = count($report->packages);
        $generated = self::escape($report->generatedAt);
        $command = self::escape($report->command);

        return <<<HTML
            <!doctype html>
            <html lang="en">
            <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>PHPStan rules on mago</title>
            <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@400;500;600&display=swap">
            <style>
            :root {
              --paper: #faf9f7; --ground: #ffffff; --ink: #1b1c1e; --muted: #6b6d73;
              --line: #e4e2dd; --rule: #f0eeea;
              --runs: #1f6b45; --refused: #9a6216; --never: #83858c;
              --runs-bg: #e6f0ea; --refused-bg: #f6efe3; --never-bg: #eeeeef;
              --tip-bg: #24262b; --tip-fg: #f2f1ef; --tip-line: #34373d;
            }
            :root:not([data-theme="light"]) { }
            @media (prefers-color-scheme: dark) {
              :root:not([data-theme="light"]) {
                --paper: #131416; --ground: #1a1b1e; --ink: #e9e8e5; --muted: #94969c;
                --line: #2b2d31; --rule: #232529;
                --runs: #6fca97; --refused: #d8a45f; --never: #8b8d94;
                --runs-bg: #17301f; --refused-bg: #322613; --never-bg: #24262a;
                --tip-bg: #2c2f35; --tip-fg: #f0efec; --tip-line: #43474e;
              }
            }
            :root[data-theme="dark"] {
              --paper: #131416; --ground: #1a1b1e; --ink: #e9e8e5; --muted: #94969c;
              --line: #2b2d31; --rule: #232529;
              --runs: #6fca97; --refused: #d8a45f; --never: #8b8d94;
              --runs-bg: #17301f; --refused-bg: #322613; --never-bg: #24262a;
              --tip-bg: #2c2f35; --tip-fg: #f0efec; --tip-line: #43474e;
            }
            * { box-sizing: border-box; }
            body { margin: 0; background: var(--paper); color: var(--ink);
                   font-family: "IBM Plex Sans", ui-sans-serif, system-ui, sans-serif;
                   font-size: 15px; line-height: 1.55; }
            .page { max-width: 62rem; margin-inline: auto; padding: 3rem 1.5rem 5rem;
                    display: flex; flex-direction: column; gap: 2.5rem; }
            header { display: flex; flex-direction: column; gap: .75rem; }
            h1 { font-size: 1.65rem; font-weight: 600; margin: 0; letter-spacing: -.015em;
                 text-wrap: balance; }
            .lede { color: var(--muted); margin: 0; max-width: 52ch; }
            .headline { display: flex; align-items: baseline; gap: .6rem;
                        font-family: "IBM Plex Mono", ui-monospace, monospace;
                        font-variant-numeric: tabular-nums; }
            .headline b { font-size: 2.6rem; font-weight: 600; line-height: 1; color: var(--runs); }
            .headline span { color: var(--muted); font-size: .9rem; }
            .meter { height: .4rem; border-radius: .2rem; background: var(--rule); overflow: hidden; }
            .meter i { display: block; height: 100%; background: var(--runs); }
            .wrap { overflow-x: auto; border: 1px solid var(--line); border-radius: .4rem;
                    background: var(--ground); }
            table { border-collapse: collapse; width: 100%;
                    font-variant-numeric: tabular-nums; font-size: .88rem; }
            th, td { text-align: right; padding: .55rem .8rem; border-bottom: 1px solid var(--rule); }
            tr:last-child td { border-bottom: 0; }
            th:first-child, td:first-child { text-align: left; }
            th:nth-child(2), td:nth-child(2) { text-align: left; }
            th { font-size: .68rem; font-weight: 600; text-transform: uppercase;
                 letter-spacing: .07em; color: var(--muted); border-bottom-color: var(--line); }
            td.pkg { font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: .82rem; }
            td.ver { color: var(--muted); font-size: .78rem;
                     font-family: "IBM Plex Mono", ui-monospace, monospace; }
            td.runs { color: var(--runs); font-weight: 600; }
            td.bar { width: 7rem; }
            td.bar i { display: block; height: .35rem; border-radius: .18rem; background: var(--runs);
                       min-width: 1px; }
            td.bar { background-image: linear-gradient(var(--rule), var(--rule));
                     background-size: calc(100% - 1.6rem) .35rem; background-repeat: no-repeat;
                     background-position: .8rem center; }
            section { display: flex; flex-direction: column; gap: .6rem; }
            h2 { font-size: .95rem; font-weight: 600; margin: 0; display: flex; flex-wrap: wrap;
                 align-items: baseline; gap: .6rem; padding-bottom: .5rem;
                 border-bottom: 1px solid var(--line);
                 font-family: "IBM Plex Mono", ui-monospace, monospace; }
            h2 small { font-family: "IBM Plex Sans", sans-serif; font-weight: 400; color: var(--muted);
                       font-size: .8rem; font-variant-numeric: tabular-nums; }
            ul { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; }
            li { display: grid; grid-template-columns: 5.4rem 1fr; gap: .1rem .8rem;
                 padding: .45rem 0; border-bottom: 1px solid var(--rule); align-items: start; }
            li:last-child { border-bottom: 0; }
            li .tag { font-size: .62rem; font-weight: 600; letter-spacing: .09em;
                      font-family: "IBM Plex Sans", sans-serif;
                      padding: .12rem .4rem; border-radius: .18rem; text-align: center;
                      margin-top: .15rem; }
            li.runs .tag { color: var(--runs); background: var(--runs-bg); }
            li.refused .tag { color: var(--refused); background: var(--refused-bg); }
            li.never .tag { color: var(--never); background: var(--never-bg); }
            li .name { font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: .82rem; }
            li p { grid-column: 2; margin: .15rem 0 0; color: var(--muted); font-size: .8rem;
                   max-width: 68ch; }
            footer { color: var(--muted); font-size: .8rem; border-top: 1px solid var(--line);
                     padding-top: 1rem; display: flex; flex-direction: column; gap: .7rem; }
            footer p { margin: 0; max-width: 76ch; }
            code { font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: .92em; }
            .def { font: inherit; color: inherit; background: none; border: 0; padding: 0;
                   cursor: help; text-transform: inherit; letter-spacing: inherit;
                   text-decoration: underline dotted currentColor; text-underline-offset: .3em; }
            .def:hover { color: var(--ink); }
            .def:focus-visible { outline: 2px solid var(--runs); outline-offset: 3px; border-radius: 2px; }
            #tip { position: fixed; z-index: 20; max-width: 22rem; margin: 0;
                   background: var(--tip-bg); color: var(--tip-fg);
                   border: 1px solid var(--tip-line); border-radius: .35rem;
                   padding: .55rem .7rem; font-size: .78rem; line-height: 1.45;
                   font-weight: 400; text-transform: none; letter-spacing: 0; text-align: left;
                   box-shadow: 0 6px 20px rgba(0, 0, 0, .18);
                   opacity: 0; visibility: hidden; transform: translateY(3px);
                   transition: opacity .12s ease, transform .12s ease; }
            #tip[data-open="true"] { opacity: 1; visibility: visible; transform: translateY(0); }
            #tip::after { content: ""; position: absolute; left: var(--arrow, 50%); bottom: -5px;
                          width: 8px; height: 8px; margin-left: -4px; transform: rotate(45deg);
                          background: var(--tip-bg);
                          border-right: 1px solid var(--tip-line);
                          border-bottom: 1px solid var(--tip-line); }
            #tip[data-below="true"]::after { bottom: auto; top: -5px; border: 0;
                          border-left: 1px solid var(--tip-line);
                          border-top: 1px solid var(--tip-line); }
            .refresh { display: flex; flex-wrap: wrap; align-items: center; gap: .5rem .7rem;
                       margin-top: .35rem; }
            .refresh code { background: var(--ground); border: 1px solid var(--line);
                            border-radius: .25rem; padding: .2rem .45rem; font-size: .78rem;
                            user-select: all; }
            .refresh button { font: inherit; font-size: .78rem; font-weight: 500; color: var(--ink);
                              background: var(--ground); border: 1px solid var(--line);
                              border-radius: .3rem; padding: .3rem .7rem; cursor: pointer; }
            .refresh button:hover { border-color: var(--muted); }
            .refresh button:focus-visible { outline: 2px solid var(--runs); outline-offset: 2px; }
            .refresh span { color: var(--muted); font-size: .78rem; }
            @media (prefers-reduced-motion: reduce) { * { transition: none !important; } }
            </style>
            </head>
            <body>
            <div class="page">
            <header>
            <h1>PHPStan rules on mago</h1>
            <div class="headline"><b>{$report->emitted()}</b><span>of {$report->portable()} portable rules run &middot; {$packages} packages installed here &middot; target <code>{$report->target}</code></span></div>
            <div class="meter"><i style="width: {$total}%"></i></div>
            <p class="lede">A rule runs when this tool could translate its body. Every rule that could not
            is listed below with the construct that stopped it. A refused rule still runs under PHPStan. It
            is only missing from mago.</p>
            <p class="lede">The denominator is this install. A figure quoting a fixed set of packages counts
            something else, so two correct numbers will differ. The table below is the configuration behind
            this one.</p>
            <div class="refresh">
              <span>Generated {$generated}. This page is a static snapshot, so re-run this to update it:</span>
              <code id="command">{$command}</code>
              <button type="button" id="refresh" data-command="{$command}">Copy</button>
            </div>
            </header>
            <div class="wrap">
            <table>
            <thead><tr><th>package</th><th>version</th>
            <th><button type="button" class="def" data-def="Every rule class in the package. The widest count, and the least useful: a package can ship a rule and wire it nowhere, and then nothing runs it.">ships</button></th>
            <th><button type="button" class="def" data-def="The rules the package wires in a neon of its own. A rule it wires nowhere cannot run for anybody, whatever this tool does with it, so the coverage figure uses this number rather than ships.">registers</button></th>
            <th><button type="button" class="def" data-def="Registered rules this tool translated. They run on mago once a worker registers the generated plugin.">runs</button></th>
            <th><button type="button" class="def" data-def="Not translated yet. The body uses a construct the vocabulary does not cover, and the reason is under the rule below. This gap can close.">refused</button></th>
            <th><button type="button" class="def" data-def="No plugin could carry this rule. It writes a build artefact, or hands a synthesised node back to PHPStan&#39;s own analysis. That is why it sits outside the denominator instead of counting as a gap.">never</button></th>
            <th></th></tr></thead>
            <tbody>
            {$rows}</tbody>
            </table>
            </div>
            {$sections}<footer>
            <p>ships counts every rule class in the package. registers counts the ones it wires in a neon
            of its own. A rule it wires nowhere cannot run for anybody, so the coverage figure uses that
            smaller number. never marks a rule no plugin could carry, which is why it sits outside the
            denominator instead of counting as a gap.</p>
            <p>These are <em>translation</em> numbers: whether this tool could carry a rule body across.
            They do not say what a rule finds. Some packages ship rules that report nothing until a project
            configures what they forbid, and those read as 0 here whether or not their bodies would
            translate. Whether a rule is worth carrying is a different question, and this page does not
            answer it.</p>
            </footer>
            </div>
            <div id="tip" role="tooltip"></div>
            <script>
            // Positioned from script and parked on the body, because the table sits in an
            // `overflow-x: auto` wrapper and anything drawn inside that gets clipped at its edge. Shown on
            // focus as well as hover, so the definitions are reachable from the keyboard.
            (function () {
              var tip = document.getElementById('tip');
              var open = null;

              function show(trigger) {
                open = trigger;
                tip.textContent = trigger.dataset.def;
                tip.dataset.open = 'true';
                tip.removeAttribute('data-below');

                var edge = trigger.getBoundingClientRect();
                var box = tip.getBoundingClientRect();
                var left = edge.left + edge.width / 2 - box.width / 2;
                var margin = 8;
                left = Math.max(margin, Math.min(left, window.innerWidth - box.width - margin));

                var top = edge.top - box.height - 10;
                if (top < margin) {
                  top = edge.bottom + 10;
                  tip.dataset.below = 'true';
                }

                tip.style.left = left + 'px';
                tip.style.top = top + 'px';
                tip.style.setProperty('--arrow', (edge.left + edge.width / 2 - left) + 'px');
                trigger.setAttribute('aria-describedby', 'tip');
              }

              function hide() {
                tip.dataset.open = 'false';
                if (open) {
                  open.removeAttribute('aria-describedby');
                  open = null;
                }
              }

              Array.prototype.forEach.call(document.querySelectorAll('.def'), function (trigger) {
                trigger.addEventListener('mouseenter', function () { show(trigger); });
                trigger.addEventListener('mouseleave', hide);
                trigger.addEventListener('focus', function () { show(trigger); });
                trigger.addEventListener('blur', hide);
                trigger.addEventListener('click', function (event) { event.preventDefault(); });
              });

              document.addEventListener('keydown', function (event) {
                if (event.key === 'Escape') { hide(); }
              });
              window.addEventListener('scroll', hide, true);
              window.addEventListener('resize', hide);
            })();

            // The page cannot re-scan on its own: the coverage numbers come from parsing every rule body,
            // which is the transpiler running, not something a static file can do. So the button hands over
            // the command instead of pretending to run it.
            //
            // `navigator.clipboard` is undefined outside a secure context, and this page is commonly served
            // over plain http from a local dev host -- where the unguarded call threw instead of degrading.
            // The command is rendered visibly and `user-select: all`, so it is obtainable whatever the
            // button manages; copying is the convenience, not the only route to it.
            (function () {
              var button = document.getElementById('refresh');
              if (!button) { return; }

              function fallback(text) {
                var field = document.createElement('textarea');
                field.value = text;
                field.setAttribute('readonly', '');
                field.style.position = 'fixed';
                field.style.opacity = '0';
                document.body.appendChild(field);
                field.select();

                var copied = false;
                try { copied = document.execCommand('copy'); } catch (error) { copied = false; }
                document.body.removeChild(field);

                return copied;
              }

              function done(ok) {
                button.textContent = ok ? 'Copied' : 'Select above';
                setTimeout(function () { button.textContent = 'Copy'; }, 1800);
              }

              button.addEventListener('click', function () {
                var text = button.dataset.command;
                if (navigator.clipboard && navigator.clipboard.writeText) {
                  navigator.clipboard.writeText(text).then(
                    function () { done(true); },
                    function () { done(fallback(text)); }
                  );

                  return;
                }

                done(fallback(text));
              });
            })();
            </script>
            </body>
            </html>

            HTML;
    }

    private static function escape(string $text): string
    {
        return htmlspecialchars($text, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }
}
