<?php

declare(strict_types=1);

namespace Sandermuller\PhpstanToMago;

/**
 * The worker that turns emitted plugins into rules mago actually runs.
 *
 * A generated plugin is a class in a file and nothing more. Mago runs PHP extensions as worker processes,
 * so until something registers the plugin in a worker and `mago.toml` names that worker, an emitted rule
 * reports nothing. Writing this by hand was the step between "the tool emitted 38 rules" and "38 rules run",
 * and it is the step that was only documented rather than done.
 *
 * Two files, and the split matters:
 *
 * - `worker.php` is **generated and owned by this tool**. It is overwritten on every run, so a consumer who
 *   edits it loses the edit on the next emit. The override point is the constructor arguments, which is why
 *   the configured parameters are written into it as a comment rather than left in `manifest.json` only.
 * - `mago.toml` is **the consumer's file and is never written**. The snippet goes to a separate file for
 *   them to paste. A tool that edits a config it does not own is one that silently reverts a hand edit, and
 *   this repository has already lost work to exactly that.
 */
final class WorkerScaffold
{
    /** Written beside the generated plugins, so a relative require from the worker resolves. */
    public const string WORKER = 'worker.php';

    public const string CONFIG_SNIPPET = 'mago.toml.snippet';

    /**
     * The autoloader is written as an absolute path rather than as `__DIR__ . '/../vendor/autoload.php'`.
     * That relative form only resolves when `--out` happens to sit one level under the project root, and a
     * worker that cannot find its autoloader fails with a class-not-found that names the plugin rather than
     * the path -- which reads as a bad plugin. Found by running a generated worker under mago rather than by
     * reading it: the file looked right.
     *
     * @param list<array{name: string, arguments: array<string, mixed>}> $rules the emitted rules, by name
     */
    public static function worker(
        array $rules,
        string $pluginDirectory,
        string $identifier,
        string $autoload,
    ): string {
        if ($rules === []) {
            throw new Refusal('no emitted rules to register in a worker');
        }

        $requires = '';
        $constructions = '';
        foreach ($rules as $rule) {
            $requires .= sprintf("require __DIR__ . '/%s/%s.php';\n", $pluginDirectory, $rule['name']);

            // Constructed with no arguments, which is the rule package's own defaults. Named here rather than
            // left in the manifest because a consumer overriding a threshold has to know the parameter exists,
            // and reading emitted code to find one is not a documented interface.
            $overrides = $rule['arguments'] === []
                ? ''
                : '  // ' . implode(', ', array_map(
                    static fn (string $name, mixed $default): string => '$' . $name . ' = ' . self::literal($default),
                    array_keys($rule['arguments']),
                    $rule['arguments'],
                ));

            $constructions .= sprintf("        new %s(),%s\n", $rule['name'], $overrides);
        }

        $uses = '';
        foreach ($rules as $rule) {
            $uses .= sprintf("use Transpiled\\%s;\n", $rule['name']);
        }

        return <<<PHP
            <?php

            declare(strict_types=1);

            // GENERATED by phpstan-to-mago. Overwritten on the next run -- do not edit.
            //
            // Override a rule's configuration by passing arguments where the constructor is called below,
            // then keep your copy outside this file. The commented parameters are the rule package's own
            // defaults, which is what a no-argument construction gives you.

            {$uses}use Mago\\Sdk\\Extension;
            use Mago\\Sdk\\Worker;

            require '{$autoload}';
            {$requires}
            (new Worker(new Extension(
                identifier: '{$identifier}',
                name: 'Transpiled PHPStan rules',
                version: '0.0.0',
                analyzerPlugins: [
            {$constructions}    ],
            )))->run();

            PHP;
    }

    /**
     * The `mago.toml` block that points at the worker.
     *
     * Written to its own file rather than into `mago.toml`. See the class docblock: this tool does not edit
     * a config it does not own.
     */
    public static function configSnippet(string $workerPath, string $identifier): string
    {
        return <<<TOML
            # Paste this into your mago.toml. phpstan-to-mago does not edit that file.
            #
            # A generated plugin lives in the `Transpiled` namespace and is enabled by default, so
            # `analyzer.plugins` needs no entry. Findings report under `{$identifier}/<rule>/<phpstan-identifier>`.

            [extension-hosts.transpiled]
            command = ["php", "{$workerPath}"]

            TOML;
    }

    /** A PHP literal for a configured default, for the comment that names the override point. */
    private static function literal(mixed $value): string
    {
        if (is_array($value)) {
            return '[' . implode(', ', array_map(self::literal(...), $value)) . ']';
        }

        if (is_string($value)) {
            return "'" . str_replace("'", "\\'", $value) . "'";
        }

        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        return $value === null ? 'null' : (string) (is_scalar($value) ? $value : '?');
    }
}
