<?php

declare(strict_types=1);

namespace Sandermuller\PhpstanToMago\Tests\Unit;

use PHPUnit\Framework\TestCase;
use Sandermuller\PhpstanToMago\RulePaths;
use Sandermuller\PhpstanToMago\Transpiler;
use Throwable;

/**
 * The census: what this transpiler does with every rule in the corpus, pinned as a file.
 *
 * The snapshots under `Fixtures/expected` pin what one rule *emits*. This pins the outcome for *all* of
 * them — emitted, or refused with which reason — which is the only thing that turns an upstream change into
 * a readable diff instead of a scattered failure somewhere else in the suite.
 *
 * It matters because `composer.lock` is not committed, so every CI run resolves the rule packages afresh.
 * An upstream release that adds a rule, deletes one, or rewrites one into a shape the vocabulary does not
 * cover shows up here as a one-line diff naming it. Without this the same release either passes silently
 * (a new rule nobody translated) or fails in whichever test happened to touch it.
 *
 * Two deliberate choices about what the census does *not* record:
 *
 * - **No package versions.** A bump that changes nothing about the translation would otherwise fail, and a
 *   drift alert that fires on every routine bump is one nobody reads.
 * - **No line numbers.** They are stripped from refusal reasons, because a construct moving down a file is
 *   not drift. Which construct blocks a rule is; that stays.
 *
 * The census is for the `php` target, the one the package ships. A count without its target invites two
 * correct numbers to look like a contradiction.
 */
final class TracksUpstreamDriftTest extends TestCase
{
    private const string CENSUS = __DIR__ . '/../Fixtures/expected/census.md';

    /**
     * The packages CI can install, which is what the census can speak for.
     *
     * `hihaho/phpstan-rules` is deliberately absent: it is not a dependency of this package, so a hosted
     * runner cannot resolve it and a census including it would pass or fail depending on whose machine ran
     * it. Its three emitted rules are covered by the corpus differential instead.
     *
     * @var list<string>
     */
    private const array PACKAGES = [
        'symplify/phpstan-rules',
        'tomasvotruba/type-coverage',
        'tomasvotruba/cognitive-complexity',
    ];

    protected function setUp(): void
    {
        Transpiler::$target = 'php';
        Transpiler::$survey = false;
        Transpiler::$allowUnverifiedAggregates = false;
    }

    public function test_the_corpus_still_translates_the_way_the_census_says(): void
    {
        $census = $this->census();
        $committed = is_file(self::CENSUS) ? (string) file_get_contents(self::CENSUS) : '';

        if ($census !== $committed) {
            file_put_contents(self::CENSUS . '.actual', $census);
        }

        $this->assertSame(
            $committed,
            $census,
            "The corpus no longer translates the way the census records.\n\n"
            . 'This is the upstream-drift alarm, and the diff names what moved: a rule added, a rule removed, '
            . 'or a rule whose body changed into (or out of) a shape the vocabulary covers. Read it, decide '
            . 'whether the new outcome is right, and only then replace the census with the .actual file beside '
            . 'it — the same discipline the emitted-output snapshots hold to.',
        );
    }

    public function test_the_census_is_not_empty_by_accident(): void
    {
        // Guards the guard. If the packages are not installed, every rule vanishes and the census becomes a
        // header — which would compare equal to a census someone regenerated in that state, and the alarm
        // would be permanently silent.
        $this->assertGreaterThan(100, substr_count($this->census(), "\n"));
        $this->assertStringContainsString('EMIT    UppercaseConstantRule', $this->census());
    }

    /** The census text: every rule in every installed package, with what this transpiler does with it. */
    private function census(): string
    {
        $lines = [
            '# Corpus census',
            '',
            'GENERATED by tests/Unit/TracksUpstreamDriftTest.php for the `php` target. Do not edit by hand.',
            '',
            'One line per rule in the packages this repository installs. A diff here is upstream drift: a rule',
            'added, removed, or rewritten into a shape the vocabulary does or does not cover.',
        ];

        foreach (self::PACKAGES as $package) {
            $source = dirname(__DIR__, 2) . '/vendor/' . $package . '/src';
            $outcomes = [];
            foreach (RulePaths::expand(is_dir($source) ? [$source] : []) as $file) {
                $name = basename($file, '.php');
                $outcomes[$name] = $this->outcome($file);
            }

            // Sorted by name, because `RulePaths` walks the filesystem and its order is not the same on every
            // machine — an unsorted census would diff against itself between a laptop and a runner.
            ksort($outcomes);

            $emitted = count(array_filter($outcomes, static fn (string $outcome): bool => $outcome === 'EMIT'));
            $lines[] = '';
            $lines[] = sprintf(
                '## %s — %d emitted, %d refused',
                $package,
                $emitted,
                count($outcomes) - $emitted,
            );
            $lines[] = '';
            foreach ($outcomes as $name => $outcome) {
                $lines[] = $outcome === 'EMIT' ? "EMIT    {$name}" : "REFUSE  {$name}: {$outcome}";
            }
        }

        return implode("\n", $lines) . "\n";
    }

    /** `EMIT`, or the refusal's reason with line numbers stripped. */
    private function outcome(string $file): string
    {
        try {
            (new Transpiler($file))->transpile();

            return 'EMIT';
        } catch (Throwable $throwable) {
            return trim((string) preg_replace('/ \(line \d+\)/', '', $throwable->getMessage()));
        }
    }
}
